version: 2.1

jobs:
  say-hello:
    steps:
      - checkout
      - run:
          name: "Build"
          command: "ssh $SSH_USER@$SSH_HOST "cd /var/www/production && git checkout ./ && git pull && npm run build""

workflows:
  say-hello-workflow:
    jobs:
      - say-hello