version: 2.1

jobs:
  deploy:
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /var/www/production && git checkout ./ && git pull && npm run build"

workflows:
  build-and-deploy:
  jobs:
    - deploy:
        branches:
          only: main # only deploy on the main branch