version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_USER@$SSH_HOST -p $SSH_PORT "cd /var/www/production && git checkout ./ && git pull && npm run build"

workflows:
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main